export const image = [
  { name: "Chupetin Trujillo", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRKFQDABRdiVznlP3YCttBlFQxSb2t-DME-nw&s", cont: 0 },
  { name: "Pantera del callao", src: "https://pbs.twimg.com/media/FG_9ESEWQA4kWPX.jpg:large", cont: 0 },
  { name: "Makanaky", src: "https://www.expreso.com.pe/wp-content/uploads/2023/12/MAKANAKI.jpg", cont: 0 },
  { name: "Alberto Fujimori", src: "https://e00-elmundo.uecdn.es/elmundo/imagenes/2007/12/11/1197320920_0.jpg", cont: 0 },
  { name: "Yuca", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRR3vZl3b5qRKTASP14ti6_5G8x1oytHd_bnA&s", cont: 0 },
  { name: "Alan García", src: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c8/Alan_Garc%C3%ADa_presidente_del_Per%C3%BA.jpg/220px-Alan_Garc%C3%ADa_presidente_del_Per%C3%BA.jpg", cont: 0 },
  { name: "Alberto Toledo", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRQHVb6qEaLT5fiPCppn1FVu-nrzPdVYzFosQ&s", cont: 0 },
  { name: "Ollanta Humala", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWpIEmksPpa4du_rGivsigTyrI7Qf6_Mf77g&s", cont: 0 },
  { name: "Pedro Pablo Kuczynski", src: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Pedro_Pablo_Kuczynski_2016_%28cropped%29.jpg/220px-Pedro_Pablo_Kuczynski_2016_%28cropped%29.jpg", cont: 0 },
  { name: "Martín Vizcarra", src: "https://pbs.twimg.com/ext_tw_video_thumb/1769769536318754818/pu/img/aSg3QQutvgxPIZoG.jpg", cont: 0 },
  { name: "Pedro Castillo", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPfOD094b89wswW11nYuEA_wjHVmEGhtnxDA&s", cont: 0 },
  { name: "Dina Boluarte", src: "https://panamericana.pe/mrf4u/statics/i/ps/img.panamericana.pe/noticia/2024/04/orig-1712367387426.jpg?width=1200&enable=upscale", cont: 0 },
  { name: "Christian Cueva", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkLcQqVgw9VAUW9xkhoVwyYycxiI24Y12vow&s", cont: 0 },
  { name: "Christian Domínguez", src: "https://www.expreso.com.pe/wp-content/uploads/2024/02/Christian-Dominguez-contento-por-apoyo-de-sus-seguidores.jpg", cont: 0 },
  { name: "Jorge Luna", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS3n_ywJgnuKsoe6wWFiAyv6Dw1oUjNFzhJ5Q&s", cont: 0 },
  { name: "Ricardo Mendoza", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlAgqugKH4-bMO7L0Fw76y1-6ZE2A4KE9oZw&s", cont: 0 },
  { name: "Sideral Luján Carrión", src: "https://www.infobae.com/new-resizer/IZdSCWJPT9s0u2c16cYyCDBW8Tc=/arc-anglerfish-arc2-prod-infobae/public/H4KDNLXATBGW5NPXJUJS5I3OQY.jpg", cont: 0 },
  { name: "Henry Spencer", src: "https://elcomercio.pe/resizer/W0oh68p5YdF2HUIHcnUaMTO1nPk=/1200x900/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/PF42B45GA5CCBN3ZRTYNYC3V2I.jpeg", cont: 0 },
  { name: "Chibolin", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYZSCjXtlVwnpnflzauAyu3Gl2bJdW1cq8Ow&s", cont: 0 },
  { name: "Magaly Medina", src: "https://peru21-pe.b-cdn.net/sites/default/efsfiles/2024-04/F7OWI374FNE3NJNROUOOCGHPIY.jpg", cont: 0 },
  { name: "Cachin", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTyXO63CfrGrEPxIyT4LW44uGUzxJtoLp9PfA&s", cont: 0 },
  { name: "Machin Alberto", src: "https://e.radio-grpp.io/normal/2022/09/30/054005_1323357.jpg", cont: 0 },
  { name: "Zorro Supe", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1xZ-Ie06xdlUSgleFPRPNSShj6JpFFCNINw&s", cont: 0 },
  { name: "Carlos Cacho", src: "https://ojo.pe/resizer/FEm2p7DzwFaO2WLQgFlS6Zc0G_Q=/580x330/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/P7FZK6XSR5E4FN5IB45IXAFEEM.jpg", cont: 0},
  { name: "Zumba", src: "https://elcomercio.pe/resizer/6XJ9Ih1SkQ6-HqpuUBW3Ifa0Aqk=/1200x900/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/7TQMZY3EPRGDXJGTMOMIAWNRHI.jpeg", cont: 0},
  { name: "Dayanita", src: "https://somosperiodismo.com/wp-content/uploads/2023/03/Portada-Dayanita-editada.jpg", cont: 0 },
  { name: "Tomate Barraza", src: "https://statics.exitosanoticias.pe/2023/09/crop/650223b49bcd1__400x209.webp", cont: 0 },
  { name: "La Uchulu", src: "https://elcomercio.pe/resizer/v2/LQ34U4GNOZCUXFJQA3SPIIEYS4.jpg?auth=e7ed57c59c3289e25f2160b6dc1ee96bd20089aedf6c3db06172a695eb256ea3&width=1200&height=680&quality=75&smart=true", cont: 0 },
  { name: "Metiche", src: "https://elcomercio.pe/resizer/4eCpqbMcFiJIFcs1mA5Ue76I76E=/1200x1200/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/N66T2RDXMRG65HF6NH7MZTCGAU.jpg", cont: 0 },
  { name: "Melcolchita", src: "https://peru21-pe.b-cdn.net/sites/default/efsfiles/2024-09/melcochita.jpg", cont: 0 },
  { name: "Susy Díaz", src: "https://e.rpp-noticias.io/xlarge/2023/10/14/075607_1487399.webp", cont: 0 },
  { name: "Andy V", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSYXJV4UPhWF5pO0oMUhKjOHkoxFxPVMb5scw&s", cont: 0 },
  { name: "Paisana Jacinta", src: "https://ichef.bbci.co.uk/ace/ws/640/cpsprodpb/1285D/production/_99196857_jacinta-1.jpg.webp", cont: 0 },
  { name: "Mayimbú", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlYLsgBc03lotDb_FQFxMgPOFM_pOw_8c0aA&s", cont: 0 },
  { name: "Robotín", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQoxZySOQ-xJDLz_O7K46cohWbA27xcfb_RxA&s", cont: 0 },
  { name: "Abimael Guzmán", src: "https://cdn.www.gob.pe/uploads/document/file/3922671/abimael.jpg.jpg", cont: 0 },
  { name: "Cesar Acuña", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRm0ir_I9uj7SY4t-ojHkqSj7Px0_2yIOQhBw&s", cont: 0 },
  { name: "Keiko Fujimori", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtoBNLJoYROtSpNkH_ZZc4TOkd8XtTfv-LBw&s", cont: 0 },
  { name: "Tongo", src: "https://portal.andina.pe/EDPfotografia3/Thumbnail/2017/02/21/000405608W.jpg", cont: 0 },
  { name: "Chaparro Chuacheneger", src: "https://elcomercio.pe/resizer/LOvS7TfA35BtTz6UkvlEQy71qr8=/1200x1200/smart/filters:format(jpeg):quality(75)/cloudfront-us-east-1.images.arcpublishing.com/elcomercio/KBQSIDQCHRDC7HUU5ALGJVDAXI.jpg", cont: 0 },
  { name: "Patricio Parodi", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUg9nbzxkRlumqw6zCkQBOmfAPtAshhxlcMQ&s", cont: 0 },
  { name: "Guty Carrera", src: "https://pbs.twimg.com/ext_tw_video_thumb/1451310017597124609/pu/img/080FT5hi0uPcDWET.jpg", cont: 0 },
  { name: "Ricolasss", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrKPlFd1BunWWZYW1C2Mp5Z7FbKjJPWRz0Xw&s", cont: 0 },
  { name: "Joel Gonzales", src: "https://i.pinimg.com/736x/54/d4/a5/54d4a53922cfea4a361a706f75190ebb.jpg", cont: 0 },
  { name: "Jimmy Santi", src: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTVDqFK5rd_2vuXRs1PFpYWY5Tt_527wix-kg&s", cont: 0 },
  { name: "Peluchin", src: "https://cloudfront-us-east-1.images.arcpublishing.com/infobae/AIQOHW4FFBBILBPT6VNVQYSOG4.jpg", cont: 0 },
]
//{ name: "", src: "", cont: 0 },
